# Generated by Django 5.1.6 on 2025-03-17 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_backend_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SadhanaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up_time', models.TimeField()),
                ('rounds_chanted', models.IntegerField()),
                ('hours_studied_college', models.FloatField()),
                ('card_filled_at', models.DateTimeField()),
                ('day_rest', models.CharField(max_length=255)),
                ('seva', models.CharField(max_length=255)),
                ('cleanliness', models.CharField(max_length=255)),
                ('book_reading_sp', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
