# Generated by Django 5.1.6 on 2025-03-17 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_sadhanaentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadhanaentry',
            name='card_filled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
